ramon: cwd                  /home/gh1/A/_work/z3-poly-testing/z3-poly-testing
ramon: start                Sat Oct 26 15:01:50 2024
ramon: nproc                32
ramon: sys.mem              63442 MiB
ramon: sys.mem.free         26462 MiB
ramon: sys.mem.avail        62608 MiB
ramon: sys.nprocs           3045
ramon: argv                 0 = z3
ramon: argv                 1 = inputs/QF_NIA_SAT/From_T2__fun9.t2__p1302_edge_closing_0.smt2
ramon: argv                 2 = -T:20
ramon: argv                 3 = -v:2
ramon: argv                 4 = -st
ramon: argv                 5 = tactic.default_tactic=(then simplify propagate-values solve-eqs simplify smt)
ramon: argv                 6 = sat.smt=true
ramon: argv                 7 = model_validate=true
ramon: childpid             490462
(sat.copy :learned 0)
(sat.solver)
(sat.copy :learned 0)
(sat.stats   :conflicts  :restarts        :learned/bin    :gc          :time)
(sat.stats          :decisions :clauses/bin     :units        :memory       )
(sat.stats      0      0    0  1152/1019     0/0  25       0    20.43   0.00)
ASSERTION VIOLATION
File: ../src/sat/smt/arith_solver.cpp
Line: 1276
Failed to verify: s().value(c) != l_true

Z3 4.13.3.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
ramon: end                  Sat Oct 26 15:01:51 2024
ramon: root.execname        z3
ramon: root.utime           0.420s
ramon: root.stime           0.000s
ramon: group.total          0.433s
ramon: group.utime          0.429s
ramon: group.stime          0.004s
ramon: group.mempeak        28940KiB
ramon: group.pidpeak        2
ramon: status               exited
[31mramon: exitcode             114[0m
ramon: walltime             0.502s
ramon: loadavg              0.86
